spring.datasource.url=jdbc:postgresql://localhost:5432/techregistry
spring.datasource.username=postgres
spring.datasource.password=Root@123

spring.jpa.show-sql=true

api.security.token.secret=12345678