spring.application.name=techregistry

# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/techregistry
spring.datasource.username=postgres
spring.datasource.password=Root@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Seguranca
api.security.token.secret=${JWT_SECRET:12345678}