spring.application.name=techregistry
# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (Render or local fallback)
# If environment variables are not set, use the local Postgres defaults below
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/techregistry}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Root@123}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true

# ===============================
# SECURITY
# ===============================
# If JWT_SECRET is not defined in the environment, fall back to a local secret for development
api.security.token.secret=${JWT_SECRET:minha_chave_secreta_local_123}